{% set name = "clarabel" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9da56f522806a847f3ece08f5f21fab7506eec3148b22446190de5206dd1e6f

build:
  number: 0
  skip: true  # [py<37]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - crossenv                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - maturin                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin
    - python
    - pip
  run:
    - python

test:
  files:
    - example_qp.py
    - example_sdp.py
  imports:
    - clarabel
  commands:
    - pip check
    - python example_qp.py
    - python example_sdp.py
  requires:
    - pip
    - numpy
    - scipy
    - python

about:
  home: https://oxfordcontrol.github.io/ClarabelDocs/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: 'Python interface for Clarabel: Interior Point Conic Optimization Solver'
  description: |
    Clarabel is an interior point numerical solver for convex optimization problems implemented
    in Rust.  It solves linear programs (LPs), quadratic programs (QPs), second-order cone programs 
    (SOCPs) and semidefinite programs (SDPs). It also solves problems with exponential, power
    cone and generalized power cone constraints.
  doc_url: https://oxfordcontrol.github.io/ClarabelDocs/
  dev_url: https://github.com/oxfordcontrol/Clarabel.rs

extra:
  recipe-maintainers:
    - goulart-paul
